export default Object.freeze({
    FETCH_TODOS:         'FETCH_TODOS',
    FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
    FETCH_TODOS_FAIL:    'FETCH_TODOS_FAIL',

    CREATE_TODO:         'CREATE_TODO',
    CREATE_TODO_SUCCESS: 'CREATE_TODO_SUCCESS',
    CREATE_TODO_FAIL:    'CREATE_TODO_FAIL',

    DELETE_TODO: 'DELETE_TODO',

    EDIT_TODO: 'EDIT_TODO',

    TOGGLE_COMPLETED: 'TOGGLE_COMPLETED',

    TOGGLE_UNCOMPLETED: 'TOGGLE_UNCOMPLETED',

    ADD_TO_FAVOURITES: 'ADD_TO_FAVOURITES',

    DELETE_FROM_FAVOURITES: 'DELETE_FROM_FAVOURITES',

});
