export default Object.freeze({
    FETCH_TODOS:         'FETCH_TODOS',
    FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
    FETCH_TODOS_FAIL:    'FETCH_TODOS_FAIL',

    CREATE_TODO:         'CREATE_TODO',
    CREATE_TODO_SUCCESS: 'CREATE_TODO_SUCCESS',
    CREATE_TODO_FAIL:    'CREATE_TODO_FAIL',

    DELETE_TODO:         'DELETE_TODO',
    DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
    DELETE_TODO_FAIL:    'DELETE_TODO_FAIL',

    EDIT_TODO:         'EDIT_TODO',
    EDIT_TODO_SUCCESS: 'EDIT_TODO_SUCCESS',
    EDIT_TODO_FAIL:    'EDIT_TODO_FAIL',

    COMPLETE_TODO:         'COMPLETE',
    COMPLETE_TODO_SUCCESS: 'COMPLETE_SUCCESS',
    COMPLETE_TODO_FAIL:    'COMPLETE_FAIL',

    ADD_TO_FAVOURITES: 'ADD_TO_FAVOURITES',

    DELETE_FROM_FAVOURITES: 'DELETE_FROM_FAVOURITES',

});
