export default Object.freeze({

    CREATE_TODO: 'CREATE_TODO',

    DELETE_TODO: 'DELETE_TODO',

    EDIT_TODO: 'EDIT_TODO',

    TOGGLE_COMPLETED: 'TOGGLE_COMPLETED',

    TOGGLE_UNCOMPLETED: 'TOGGLE_UNCOMPLETED',

    ADD_TO_FAVOURITES: 'ADD_TO_FAVOURITES',

    DELETE_FROM_FAVOURITES: 'DELETE_FROM_FAVOURITES',

});
